### ISSUE TITLE
Email is not sent without cron in `daemon` mode

### ISSUE THREAD

**Issue by spysir** [slurdge/goeland#118]
This is my config.toml
```yaml
loglevel = "info"
dry-run = false
run-at-startup = true
purge-days = 5

[email]
host = "smtp.xxx.com"
port = 2525
authentication = "none"

[sources]

[sources.hackernews]
url = "https://hnrss.org/newest"
type = "feed"
filters = ["all", "today"]
allow-insecure = false

[pipes]

[pipes.hackernews]
disabled = false
source = "hackernews"
destination = "email"
email_to = ["a@a.com", "b@b.com"]
email_from = ["c@c.com"]
```
When running 'docker-compose up -d' ,Goeland sends an email, but the feeds will be  updated in the future no email will be sent

**Comment by slurdge** [comment]
Hello @spysir , this is normal, it's because you don't have a `cron` inside your pipe.
You need to add it like this:
```toml
[pipes.hackernews]
disabled = false
source = "hackernews"
destination = "email"
email_to = ["a@a.com", "b@b.com"]
email_from = ["c@c.com"]
cron = "30 12 * * *" #execute the schedule every day at 12h30
```
We lack documentation for this feature. You are among the first to use docker in daemon mode I think, most people are using a cron with the executable directly. Please inform me if it works correctly !
For cron syntax, you can use https://crontab.guru 
Also you can check your logs, if a schedule is detected, it will be shown inside the logs.
To finish, you don't need `disabled = false`, pipes are enabled by default.
