### ISSUE TITLE
includelink filter doesn't work

### ISSUE THREAD

**Issue by joe2xyz** [slurdge/goeland#212]
Hi folks,

Thank you for Goeland. It's FANTASTIC software!!!

I'm trying to get rss2email experience - by getting a single e-mail per each new post in RSS feed.

I configured Goeland like this:

``` toml
...

[sources.xyz]
url = "https://.../"
type = "feed"
filters = ["unseen", "retrieve", "includesourcetitle", "includelink", "untrack"]
allow-insecure = false

...

[pipes.xyz]
disabled = false
source = "xyz"
destination = "email"
email_title = "xyz: {{.EntryTitle}}"
email_to = ["to@example.com"]
email_cc = []
email_bcc = []
email_from = "xyz <from@example.>"
# email_title =

...
```

But I'm getting e-mails with plain text - with no links to the post.

Is it a bug?

Thank you.

**Desktop**
 - OS: Linux
 - Browser: firefox
 - Version: goeland 0.18.3
