### ISSUE TITLE
results from Nitter feeds don't include the tweet author

### ISSUE THREAD

**Issue by kylrth** [slurdge/goeland#35]
With the following pipe definition:

```toml
[sources.lexfridman]
url = "https://nitter.nl/lexfridman/search/rss?f=tweets&e-replies=on"
type = "feed"
filters = ["unseen", "links", "includelink", "digest"]
```

I get an email that looks like this:

<img src="https://user-images.githubusercontent.com/5044802/170046734-d4e560a1-8ce3-49e7-9915-b9a35d5c5d98.png" width="400" />

As you can see, the tweet body appears as both the title and the content. I'd ideally like the title to be the tweet author name (which may be different from @lexfridman in the case of retweets or if I'm making a digest of multiple Twitter users), and then let the body be the same.

I know you've got that `replace` filter for simple text manipulation in the body, but have you got any ideas about more complex field manipulation that might make it possible to insert the `<dc:creator>` tag into the title or something like that?
