### ISSUE TITLE
morss URL isn't showing up in seen entry key

### ISSUE THREAD

**Issue by kylrth** [slurdge/goeland#38]
With the following source:

```toml
[sources.apnews]
url = "https://rss.kylrth.com/:proxy:items=||*[class=content]||p/https://apnews.com/apf-topnews"
type = "feed"
filters = ["unseen", "lasthours", "links", "includelink", "combine(3)"]
```

I get the following logs:

```logs
Executing pipe named: apnews
Fetching source: apnews of type feed
Retrieved 10 feeds for source apnews
Executing unseen filter with args: []
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
already seen entry with key: apnews/
After unseen: 0 feeds
After unseen: []
Executing lasthours filter with args: []
After lasthours: 0 feeds
After lasthours: []
Executing links filter with args: []
After links: 0 feeds
After links: []
Executing includelink filter with args: []
After includelink: 0 feeds
After includelink: []
Executing combine filter with args: [3]
After combine(3): 0 feeds
After combine(3): []
&{apnews Top News: US & International Top News Stories Today | AP News []}
```

running with `v0.10.2` in Docker.
